# Generated by Django 4.1.3 on 2022-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='imag',
            field=models.TextField(default='null', max_length=350),
            preserve_default=False,
        ),
    ]
